substitutions:
  device_name: Haier AC

esphome:
  name: haier
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m

external_components:
  source:
    type: local
    path: ./components

uart:
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3
  id: ac_port  
    
logger:
  level: DEBUG
  baud_rate: 0

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

api:

ota:

climate:
  - platform: haier
    name: ${device_name} 
    uart_id: ac_port
